config/routes.rb
DylanHustedCom::Application.routes.draw do
  root 'home#home'
  resources :startups, only: [:show, :index]
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/press',   to: 'static_pages#press',   via: 'get'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  validates_presence_of :name, :bio, :description, :full_logo, :square_logo, :stage
  default_scope -> { order('id ASC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  	@idea_stage = Startup.where(stage: 'idea')
  	@research_stage = Startup.where(stage: 'research')
  	@financing_stage = Startup.where(stage: 'financing')
  	@development_stage = Startup.where(stage: 'development')
  	@launch_stage =  Startup.where(stage: 'launch')
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  def new
    @startup = Startup.new		
  end

  def create
  	@startup = Startup.new(startup_params)
  end

  def show
  	@startup = Startup.find(params[:id])
  end

  def index
    @idea_stage = Startup.where(stage: 'idea')
    @research_stage = Startup.where(stage: 'research')
    @financing_stage = Startup.where(stage: 'financing')
    @development_stage = Startup.where(stage: 'development')
    @launch_stage =  Startup.where(stage: 'launch')
  end

  private

    def startup_params
      params.require(:startup).permit(:name, :bio, :description, :website, :links, :full_logo, :square_logo, :stage)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def press
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
    base_title = "Dylan Husted"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/_live_startups.html.erb
<div class="idea-stage">
	<% @idea_stage.each do |startup| %>
		<%= link_to image_tag(startup.square_logo, class: 'square-logo'), startup_path(startup.id) %>
	<% end %>
</div>
<div class="research-stage">
	<% @research_stage.each do |startup| %>
		<%= link_to image_tag(startup.square_logo, class: 'square-logo'), startup_path(startup.id) %>
	<% end %>
</div>
<div class="financing-stage">
	<% @financing_stage.each do |startup| %>
		<%= link_to image_tag(startup.square_logo, class: 'square-logo'), startup_path(startup.id) %>
	<% end %>
</div>
<div class="development-stage">
	<% @development_stage.each do |startup| %>
		<%= link_to image_tag(startup.square_logo, class: 'square-logo'), startup_path(startup.id) %>
	<% end %>
</div>
<div class="launch-stage">
	<% @launch_stage.each do |startup| %>
		<%= link_to image_tag(startup.square_logo, class: 'square-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
</div>

app/views/home/home.html.erb
<%= provide(:title, "Home") %>
<div class="top-h-wrapper home-top-h-wrapper">
	<h1>Full Stack Tech Entrepreneur</h1>
	<h2>Ideation • Research • Design • Development • Marketing</h2>
</div>
<div class="pipeline-wrapper">
	<%= render 'live_startups' %>
</div>	

app/views/layouts/_footer.html.erb
<footer>
<div class="footer-left">
	<%= link_to 'Home', root_path %>
	&nbsp;&nbsp;&nbsp;
	<%= link_to 'About', about_path %>
	&nbsp;&nbsp;&nbsp;
	<%= link_to 'Contact', contact_path %>
</div>	
<div class="footer-middle">© Dylan Husted 2015</div>
<div class="footer-right">	
	<%= link_to 'Startups', startups_path %>
	&nbsp;&nbsp;&nbsp;
	<%= link_to 'Press', press_path %>
	&nbsp;&nbsp;&nbsp;
	<%= link_to 'Blog', 'https://www.saveohno.org/blog' %>
</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "custom", media: "screen and (min-width: 1100px)", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "mobile", media: "screen and (max-width: 1100px)", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<div class="stripe">&nbsp;</div>
<div class="dylan">
	<%= link_to image_tag('pipes_and_pic.png', class: 'pipes_and_pic'), root_url %>
	<br>
	<h1 class="name"><%= link_to 'Dylan Husted', root_url %></h1>
	<h2 class="social-media">
		<%= link_to 'Twitter', 'https://twitter.com/__________Dylan' %>
		•
		<%= link_to 'LinkedIn', 'https://www.linkedin.com/pub/dylan-husted/4b/3a9/a75' %>
		•
		<%= link_to 'GitHub', 'https://github.com/dylanhusted' %>
	</h2>
</div>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/startups/index.html.erb
<%= provide(:title, "Startups") %>
<div class="top-h-wrapper">
	<h1>Startups I'm Working On</h1>
</div>
<br>
<br>
<div class="left-push"></div>
<div class="container">
	<h1>Launched</h1>
	<br>
	<% @launch_stage.each do |startup| %>
		<%= link_to image_tag(startup.full_logo, class: 'full-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
	<br>	
	<h1>In Development</h1>
	<br>
	<% @development_stage.each do |startup| %>
		<%= link_to image_tag(startup.full_logo, class: 'full-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
	<br>
	<h1>Pursuing Financing</h1>
	<br>
	<% @financing_stage.each do |startup| %>
		<%= link_to image_tag(startup.full_logo, class: 'full-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
	<br>
	<h1>Market Research Stage</h1>
	<br>
	<% @research_stage.each do |startup| %>
		<%= link_to image_tag(startup.full_logo, class: 'full-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
	<br>
	<h1>Just An Idea</h1>
	<br>
	<% @idea_stage.each do |startup| %>
		<%= link_to image_tag(startup.full_logo, class: 'full-logo'), startup_path(startup.id) %>
		<br>
		<br>
	<% end %>
</div>

app/views/startups/show.html.erb
<%= provide(:title, "#{@startup.name}") %>
<div class="top-h-wrapper">
	<h1><%= link_to @startup.name, @startup.website %></h1>
	<h2 class="h2-grey"><%= @startup.bio %></h2>
</div>
<br>
<br>
<div class="left-push"></div>
<div class="container">
	<h1>Logo</h1>
	<div class="logo-wrapper-wrapper">
	<div class="logo-wrapper">
		<%= image_tag @startup.full_logo, alt: "#{@startup.name} - Logo", title: "#{@startup.name} - Logo", class: 'full-logo' %>
	</div>
	</div>
	<br>
	<br>
	<br>
	<br>
	<h1>Idea</h1>
	<p><%= @startup.description %></p>
	<h1>My Role</h1>
	<p><%= @startup.role %></p>
	<h1>Current Stage</h1>
	<p><%= @startup.stage.capitalize %></p>
	<h1>Relevant Links</h1>
	<%= @startup.links.html_safe if @startup.links.nil? != true %>
	<div class="center">
		<% case @startup.stage %>
		<% when 'launch' %>
		<%= link_to "Check it out!", @startup.website, class: 'btn btn-large btn-primary' %>
		<% end %>
	</div>	
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<div class="top-h-wrapper">
	<h1>About</h1>
</div>
<br>
<br>
<div class="left-push"></div>
<div class="container about-content">
	<p>I'm a tech entrepreneur, sophomore at Babson College, and (wannabe) kickboxer. I'm currently running 2 businesses with several early stage ideas in the works, studying business and entrepreneurship at Babson while teaching myself computer science, and training at the UFC gym in Boston. I LOVE tech startups and innovation.</p>
	<br>
	<p>The best term I can use to describe myself professionally is that I'm a 'Full Stack Tech Entrepreneur' (or at least aspiring to be). I constantly observe and ideate, conduct research on those ideas, and bring them to life with my design and dev skills. Once I have a product, I'm then responsible for marketing it, too. That's probably my weakpoint in the chain, but I'm working on it. I've spent a lot of time pursuing this Full Stack Tech Entrepreneur idea, and I'm finally at a point where I can bring an idea to life in under a week for less than 50 bucks. That's pretty cool.</p>
	<br>
	<p>This website, for example, was a one-day project with total costs of $10. I felt the need to create a roadmap/canvas of all the work I was doing because it was actually getting hard to keep track of it all and clearly articulate the stage of all of my ideas, their exact scope, description etc. So I created a quick wireframe of the homepage, turned that into a mockup with Illustrator and Photoshop, and then brought the full site to life with Ruby on Rails.</p>
	<br>
	<p>Like just about everyone, I'm busy. But unlike just about everyone, I'm willing to make the time to connect with you - even if you're some random person I've never met who's cold-emailing me. The biggest problem I'm facing right now is not having enough motivated people working on all of my ideas with me. So send me a note and let's talk!</p>
	<br>
	<div class="center">
		<%= link_to 'Send Me A Message', contact_path, class: 'btn btn-primary' %>
		&nbsp;
		&nbsp;
		<%= link_to 'Check Out My Startups', startups_path, class: 'btn btn-primary' %>
	</div>
</div>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<div class="top-h-wrapper">
	<h1>Contact Me</h1>
</div>
<br>
<br>
<div class="left-push"></div>
<div class="container contact-content">
	<br>
	<p>Feel free to contact me anytime at this address:</p>
	<h3>dylan [at] saveohno.org</h3>
</div>

app/views/static_pages/press.html.erb
<%= provide(:title, "Press") %>
<div class="top-h-wrapper">
	<h1>Press</h1>
</div>
<br>
<br>
<div class="left-push"></div>
<div class="container center">
<h2>Here are some blogs I've been featured in:</h2>
<%= link_to image_tag("techday-logo.png", class: 'full-logo'), "https://techdayhq.com/news/saving-the-world-one-petition-at-a-time" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("http://i159.photobucket.com/albums/t149/dhusted1/Screen%20Shot%202015-04-12%20at%204.11.20%20PM_zpskq41y9hd.png", alt: 'Babson Blog', class: 'full-logo'), "http://blogs.babson.edu/social/2015/06/17/social-innovation-showcased-in-babson-summer-startups/" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("http://bostinno.streetwise.co/assets/fdec7307/img/1/site_logo_white.png", alt: 'BostInno', class: 'full-logo'), "http://bostinno.streetwise.co/topic/saveohno/"  %>
<br>
<br>
<%= link_to image_tag("http://heapsmag.s3.amazonaws.com/wp-content/uploads/2015/04/heaps_log.png", alt: 'HEAPS Magazine', class: 'full-logo'), "http://heapsmag.com/%E5%9C%B0%E7%90%83%E3%81%AE%E6%95%91%E4%B8%96%E4%B8%BB%E3%81%AF%E3%80%81%E3%82%AD%E3%83%83%E3%82%AF%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%BF%E3%83%BC%E3%81%AB%E3%81%84%E3%81%9F%EF%BC%81/" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("https://www.eboc.co/blog/wp-content/themes/eboc/img/logo.png", alt: 'EBOC.co', class: 'full-logo'), "https://www.eboc.co/blog/8-must-download-apps-recommended-by-business-owners-0715110" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("energy-teachers.png", alt: 'EnergyTeachers.org Blog', class: 'full-logo'), "http://energyteachers.org/ReadArticle.php?id=523" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("yukai-chou-logo.png", alt: 'Yu-Kai Chou Blog', class: 'full-logo'), "http://www.yukaichou.com/gamification-guest-posts/octalysis-saveohnoorg-gamified-platform-climate-activism/#.VSrQjhPF-Ns" %>
<br>
<br>
<%= link_to image_tag("http://www.bostonherald.com/sites/all/themes/bostonherald/logo.png", alt: 'Boston Herald', class: 'full-logo'), "http://www.bostonherald.com/entertainment/lifestyle/best_life_ever/2015/10/today_know_tomorrow" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("http://change-magazine.org/wp-content/themes/change2/images/revamp/logo.png", alt: 'Change Magazine', class: 'full-logo'), "http://change-magazine.org/2015/09/know-tomorrow-student-action-on-climate-change/" %>
&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("http://thebabsonfreepress.com/wp-content/uploads/2015/10/FREEPSiteLogoFinal.png", alt: 'The Babson Free Press', class: 'full-logo'), "http://issuu.com/thebabsonfreepress/docs/free_press_november_2015/9?e=19517191/31422879" %>
</div>